<?php

return [
    'enabled' => env('HOME_VISIT_WORKFLOW_V2', true),

    'statuses' => [
        'awaiting_hospital_approval' => ['label' => 'Request Submitted'],
        'awaiting_clinician_approval' => ['label' => 'Approved Awaiting Clinician'],
        'awaiting_payment' => ['label' => 'Awaiting Payment'],
        'scheduled' => ['label' => 'Visit Confirmed'],
        'en_route' => ['label' => 'Clinician Traveling'],
        'arrived' => ['label' => 'Clinician On-Site'],
        'in_progress' => ['label' => 'Visit Ongoing'],
        'visit_completed' => ['label' => 'Visit Closed', 'terminal' => true],
        'admission_recommended' => ['label' => 'Admission Initiated'],
        'home_admission_quote_pending_hospital' => ['label' => 'Admission Pricing Review'],
        'admission_revision_requested' => ['label' => 'Admission Revision Needed'],
        'admission_rejected' => ['label' => 'Admission Declined', 'terminal' => true],
        'home_admitted_pending_payment' => ['label' => 'Admission Approved Awaiting Payment'],
        'home_admitted_active' => ['label' => 'Home Care Live'],
        'payment_due' => ['label' => 'Billing Cycle Due'],
        'payment_overdue' => ['label' => 'Payment Overdue'],
        'care_paused_non_critical' => ['label' => 'Care Paused (Non-Critical)'],
        'episode_closed_nonpayment' => ['label' => 'Episode Closed (Non-Payment)', 'terminal' => true],
        'discharge_initiated' => ['label' => 'Discharge Started'],
        'episode_completed' => ['label' => 'Episode Completed', 'terminal' => true],
        'escalation_open' => ['label' => 'Escalation Open'],
        'escalation_in_progress' => ['label' => 'Escalation Being Managed'],
        'escalation_in_transfer' => ['label' => 'Escalation Transfer Underway'],
        'escalation_resolved' => ['label' => 'Escalation Closed'],
        'admission_expired' => ['label' => 'Admission Expired'],
        'admission_cancelled' => ['label' => 'Admission Cancelled', 'terminal' => true],
        'escalation_unresolved' => ['label' => 'Escalation Unresolved'],
    ],

    'transitions' => [
        'awaiting_hospital_approval' => ['awaiting_clinician_approval', 'admission_rejected', 'admission_cancelled'],
        'awaiting_clinician_approval' => ['awaiting_payment', 'admission_cancelled'],
        'awaiting_payment' => ['scheduled', 'admission_cancelled', 'admission_expired'],
        'scheduled' => ['en_route', 'cancelled', 'no_show', 'admission_cancelled', 'escalation_open', 'escalation_in_transfer'],
        'en_route' => ['arrived', 'escalation_open', 'escalation_in_transfer', 'cancelled', 'admission_cancelled'],
        'arrived' => ['in_progress', 'no_show', 'escalation_open', 'escalation_in_transfer'],
        'in_progress' => ['visit_completed', 'admission_recommended', 'escalation_open', 'escalation_in_transfer'],
        'visit_completed' => [],
        'admission_recommended' => ['home_admission_quote_pending_hospital', 'admission_rejected'],
        'home_admission_quote_pending_hospital' => ['home_admitted_pending_payment', 'admission_rejected', 'admission_revision_requested'],
        'admission_revision_requested' => ['home_admission_quote_pending_hospital', 'admission_rejected'],
        'admission_rejected' => [],
        'home_admitted_pending_payment' => ['home_admitted_active', 'payment_overdue', 'admission_expired', 'admission_cancelled'],
        'home_admitted_active' => ['payment_due', 'discharge_initiated', 'escalation_open', 'escalation_in_transfer'],
        'payment_due' => ['home_admitted_active', 'payment_overdue', 'escalation_open', 'escalation_in_transfer'],
        'payment_overdue' => ['home_admitted_active', 'care_paused_non_critical', 'episode_closed_nonpayment', 'escalation_open', 'escalation_in_transfer', 'escalation_unresolved'],
        'care_paused_non_critical' => ['home_admitted_active', 'episode_closed_nonpayment', 'escalation_open', 'escalation_in_transfer'],
        'episode_closed_nonpayment' => [],
        'discharge_initiated' => ['episode_completed'],
        'episode_completed' => [],
        'escalation_open' => ['escalation_in_progress', 'escalation_in_transfer', 'escalation_resolved', 'escalation_unresolved'],
        'escalation_in_progress' => ['escalation_resolved', 'escalation_in_transfer', 'escalation_unresolved'],
        'escalation_in_transfer' => ['escalation_resolved', 'escalation_unresolved'],
        'escalation_resolved' => ['home_admitted_active', 'episode_completed', 'visit_completed'],
        'admission_expired' => ['home_admission_quote_pending_hospital', 'home_admitted_pending_payment', 'admission_cancelled'],
        'admission_cancelled' => [],
        'escalation_unresolved' => ['escalation_in_transfer', 'episode_completed'],
    ],

    'status_aliases' => [
        'awaiting hospital approval' => 'awaiting_hospital_approval',
        'awaiting clinician approval' => 'awaiting_clinician_approval',
        'awaiting payment' => 'awaiting_payment',
        'visit_completed' => 'visit_completed',
        'visit completed' => 'visit_completed',
        'episode completed' => 'episode_completed',
    ],

    'legacy_statuses' => [
        'requested',
        'triage',
        'insurance_pending',
        'insurance_approved',
        'insurance_rejected',
        'pending_payment',
        'scheduled',
        'in_progress',
        'completed',
        'cancelled',
        'no_show',
    ],

    'action_targets' => [
        'approve' => 'awaiting_clinician_approval',
        'reject' => 'admission_rejected',
        'request_changes' => '__dynamic_request_changes',
        'approve_assignment' => 'awaiting_payment',
        'reject_assignment' => 'admission_cancelled',
        'reassign' => '__stay',
        'pay_now' => 'scheduled',
        'prepare_for_visit' => '__stay',
        'view_eta' => '__stay',
        'get_support' => '__stay',
        'monitor_assist' => '__stay',
        'start_travel' => 'en_route',
        'mark_arrived' => 'arrived',
        'confirm_check_in' => 'in_progress',
        'start_visit' => 'in_progress',
        'complete_visit' => 'visit_completed',
        'submit_admission_plan' => 'home_admission_quote_pending_hospital',
        'approve_quote' => 'home_admitted_pending_payment',
        'request_quote_revision' => 'admission_revision_requested',
        'reject_admission' => 'admission_rejected',
        'pay_admission' => 'home_admitted_active',
        'open_escalation' => 'escalation_open',
        'escalate' => 'escalation_open',
        'resolve_escalation' => 'escalation_resolved',
        'transfer_escalation' => 'escalation_in_transfer',
        'mark_escalation_unresolved' => 'escalation_unresolved',
        'pause_care_non_critical' => 'care_paused_non_critical',
        'reinstate_care' => 'home_admitted_active',
        'close_episode_nonpayment' => 'episode_closed_nonpayment',
        'initiate_discharge' => 'discharge_initiated',
        'approve_discharge' => 'episode_completed',
        'cancel_admission' => 'admission_cancelled',
        'expire_admission' => 'admission_expired',
    ],

    'role_actions' => [
        'awaiting_hospital_approval' => [
            'patient' => ['request_changes', 'cancel_admission'],
            'hospital' => ['approve', 'reject', 'request_changes'],
        ],
        'awaiting_clinician_approval' => [
            'clinician' => ['approve_assignment', 'reject_assignment'],
            'hospital' => ['reassign', 'cancel_admission'],
        ],
        'awaiting_payment' => [
            'patient' => ['pay_now', 'cancel_admission'],
            'hospital' => ['expire_admission'],
        ],
        'scheduled' => [
            'patient' => ['prepare_for_visit'],
            'clinician' => ['start_travel', 'open_escalation'],
            'hospital' => [],
        ],
        'en_route' => [
            'patient' => ['view_eta'],
            'clinician' => ['mark_arrived', 'open_escalation'],
            'hospital' => ['open_escalation', 'cancel_admission'],
        ],
        'arrived' => [
            'patient' => ['confirm_check_in'],
            'clinician' => ['start_visit', 'open_escalation'],
            'hospital' => ['open_escalation'],
        ],
        'in_progress' => [
            'patient' => ['get_support', 'open_escalation'],
            'clinician' => ['complete_visit', 'escalate'],
            'hospital' => ['monitor_assist'],
        ],
        'visit_completed' => [
            'patient' => [],
            'clinician' => [],
            'hospital' => [],
        ],
        'admission_recommended' => [
            'patient' => [],
            'clinician' => ['submit_admission_plan'],
            'hospital' => ['reject_admission'],
        ],
        'home_admission_quote_pending_hospital' => [
            'patient' => [],
            'clinician' => ['submit_admission_plan'],
            'hospital' => ['approve_quote', 'request_quote_revision', 'reject_admission'],
        ],
        'admission_revision_requested' => [
            'patient' => [],
            'clinician' => ['submit_admission_plan'],
            'hospital' => ['reject_admission'],
        ],
        'admission_rejected' => [
            'patient' => [],
            'clinician' => [],
            'hospital' => [],
        ],
        'home_admitted_pending_payment' => [
            'patient' => ['pay_admission', 'cancel_admission'],
            'clinician' => [],
            'hospital' => ['expire_admission', 'cancel_admission'],
        ],
        'home_admitted_active' => [
            'patient' => ['open_escalation'],
            'clinician' => ['initiate_discharge', 'open_escalation'],
            'hospital' => ['initiate_discharge', 'open_escalation'],
        ],
        'payment_due' => [
            'patient' => ['pay_admission'],
            'clinician' => ['open_escalation'],
            'hospital' => ['open_escalation'],
        ],
        'payment_overdue' => [
            'patient' => ['pay_admission'],
            'clinician' => ['open_escalation'],
            'hospital' => ['pause_care_non_critical', 'close_episode_nonpayment', 'open_escalation', 'mark_escalation_unresolved'],
        ],
        'care_paused_non_critical' => [
            'patient' => ['pay_admission'],
            'clinician' => ['open_escalation'],
            'hospital' => ['reinstate_care', 'close_episode_nonpayment', 'open_escalation'],
        ],
        'episode_closed_nonpayment' => [
            'patient' => [],
            'clinician' => [],
            'hospital' => [],
        ],
        'discharge_initiated' => [
            'patient' => [],
            'clinician' => [],
            'hospital' => ['approve_discharge'],
        ],
        'episode_completed' => [
            'patient' => [],
            'clinician' => [],
            'hospital' => [],
        ],
        'escalation_open' => [
            'patient' => [],
            'clinician' => ['open_escalation', 'transfer_escalation', 'resolve_escalation', 'mark_escalation_unresolved'],
            'hospital' => ['transfer_escalation', 'resolve_escalation', 'mark_escalation_unresolved'],
        ],
        'escalation_in_progress' => [
            'patient' => [],
            'clinician' => ['transfer_escalation', 'resolve_escalation', 'mark_escalation_unresolved'],
            'hospital' => ['transfer_escalation', 'resolve_escalation', 'mark_escalation_unresolved'],
        ],
        'escalation_in_transfer' => [
            'patient' => [],
            'clinician' => ['resolve_escalation', 'mark_escalation_unresolved'],
            'hospital' => ['resolve_escalation', 'mark_escalation_unresolved'],
        ],
        'escalation_resolved' => [
            'patient' => [],
            'clinician' => [],
            'hospital' => [],
        ],
        'admission_expired' => [
            'patient' => [],
            'clinician' => ['submit_admission_plan'],
            'hospital' => ['approve_quote', 'cancel_admission'],
        ],
        'admission_cancelled' => [
            'patient' => [],
            'clinician' => [],
            'hospital' => [],
        ],
        'escalation_unresolved' => [
            'patient' => [],
            'clinician' => ['transfer_escalation'],
            'hospital' => ['transfer_escalation', 'approve_discharge'],
        ],
    ],
];
