<?php

return [
    'enabled' => env('TELETEST_WORKFLOW_V1', true),

    'statuses' => [
        'awaiting_hospital_approval' => ['label' => 'Request Submitted'],
        'hospital_changes_requested' => ['label' => 'Changes Requested'],
        'hospital_rejected' => ['label' => 'Request Rejected', 'terminal' => true],
        'awaiting_technician_approval' => ['label' => 'Awaiting Technician Confirmation'],
        'technician_rejected' => ['label' => 'Technician Declined'],
        'technician_reassignment_pending' => ['label' => 'Reassignment In Progress'],
        'awaiting_payment' => ['label' => 'Payment Required'],
        'payment_failed' => ['label' => 'Payment Failed'],
        'payment_expired' => ['label' => 'Payment Window Expired'],
        'scheduled' => ['label' => 'Visit Confirmed'],
        'reschedule_requested_by_patient' => ['label' => 'Patient Requested Reschedule'],
        'reschedule_requested_by_hospital' => ['label' => 'Hospital Requested Reschedule'],
        'reschedule_requested_by_technician' => ['label' => 'Technician Requested Reschedule'],
        'rescheduled_confirmed' => ['label' => 'Reschedule Confirmed'],
        'en_route' => ['label' => 'Technician Traveling'],
        'arrival_breach' => ['label' => 'ETA Breach'],
        'arrived' => ['label' => 'Technician On Site'],
        'in_progress' => ['label' => 'Visit Ongoing'],
        'sample_collected' => ['label' => 'Sample Collected'],
        'sample_rejected' => ['label' => 'Sample Rejected'],
        'recollection_required' => ['label' => 'Recollection Required'],
        'lab_processing' => ['label' => 'Lab Processing'],
        'result_ready' => ['label' => 'Result Ready'],
        'result_delivered' => ['label' => 'Result Delivered'],
        'visit_completed' => ['label' => 'Visit Completed'],
        'visit_closed' => ['label' => 'Visit Closed', 'terminal' => true],
        'cancelled_by_hospital' => ['label' => 'Cancelled by Hospital'],
        'cancelled_by_technician' => ['label' => 'Cancelled by Technician'],
        'no_show_patient' => ['label' => 'No Show Patient', 'terminal' => true],
        'no_show_technician' => ['label' => 'No Show Technician'],
        'payment_refund_pending' => ['label' => 'Payment Refund Pending'],
        'payment_refunded' => ['label' => 'Payment Refunded', 'terminal' => true],
        'complaint_open' => ['label' => 'Complaint Open'],
        'complaint_resolved' => ['label' => 'Complaint Resolved'],
        'audit_hold' => ['label' => 'Audit Hold'],
        'escalation_open' => ['label' => 'Escalation Open'],
        'escalation_in_progress' => ['label' => 'Escalation In Progress'],
        'escalation_in_transfer' => ['label' => 'Escalation In Transfer'],
        'escalation_resolved' => ['label' => 'Escalation Resolved'],
        'escalation_unresolved' => ['label' => 'Escalation Unresolved', 'terminal' => true],
    ],

    'allowed_transitions' => [
        'awaiting_hospital_approval' => [
            'awaiting_technician_approval',
            'hospital_changes_requested',
            'hospital_rejected',
            'cancelled_by_hospital',
        ],
        'hospital_changes_requested' => [
            'awaiting_hospital_approval',
            'hospital_rejected',
            'cancelled_by_hospital',
        ],
        'hospital_rejected' => [],
        'awaiting_technician_approval' => [
            'awaiting_payment',
            'technician_rejected',
            'technician_reassignment_pending',
            'cancelled_by_hospital',
        ],
        'technician_rejected' => [
            'technician_reassignment_pending',
            'hospital_rejected',
            'cancelled_by_hospital',
        ],
        'technician_reassignment_pending' => [
            'awaiting_technician_approval',
            'awaiting_payment',
            'technician_rejected',
            'hospital_rejected',
            'cancelled_by_hospital',
            'escalation_open',
        ],
        'awaiting_payment' => [
            'scheduled',
            'payment_failed',
            'payment_expired',
            'cancelled_by_hospital',
        ],
        'payment_failed' => [
            'awaiting_payment',
            'scheduled',
            'payment_expired',
            'cancelled_by_hospital',
        ],
        'payment_expired' => [
            'awaiting_payment',
        ],
        'scheduled' => [
            'en_route',
            'reschedule_requested_by_patient',
            'reschedule_requested_by_hospital',
            'reschedule_requested_by_technician',
            'technician_reassignment_pending',
            'cancelled_by_hospital',
            'cancelled_by_technician',
        ],
        'reschedule_requested_by_patient' => [
            'rescheduled_confirmed',
            'reschedule_requested_by_hospital',
            'scheduled',
            'cancelled_by_hospital',
        ],
        'reschedule_requested_by_hospital' => [
            'rescheduled_confirmed',
            'reschedule_requested_by_patient',
            'scheduled',
            'cancelled_by_hospital',
        ],
        'reschedule_requested_by_technician' => [
            'rescheduled_confirmed',
            'reschedule_requested_by_patient',
            'scheduled',
            'technician_reassignment_pending',
            'cancelled_by_hospital',
        ],
        'rescheduled_confirmed' => [
            'scheduled',
            'en_route',
            'technician_reassignment_pending',
        ],
        'en_route' => [
            'arrived',
            'arrival_breach',
            'technician_reassignment_pending',
            'cancelled_by_hospital',
        ],
        'arrival_breach' => [
            'en_route',
            'arrived',
            'reschedule_requested_by_patient',
            'technician_reassignment_pending',
            'rescheduled_confirmed',
            'cancelled_by_hospital',
        ],
        'arrived' => [
            'in_progress',
            'no_show_patient',
            'arrival_breach',
            'cancelled_by_hospital',
        ],
        'in_progress' => [
            'sample_collected',
            'escalation_open',
        ],
        'sample_collected' => [
            'lab_processing',
            'sample_rejected',
            'escalation_open',
        ],
        'sample_rejected' => [
            'recollection_required',
            'escalation_open',
        ],
        'recollection_required' => [
            'scheduled',
            'technician_reassignment_pending',
            'cancelled_by_hospital',
        ],
        'lab_processing' => [
            'result_ready',
            'sample_rejected',
            'audit_hold',
            'escalation_open',
        ],
        'result_ready' => [
            'result_delivered',
            'audit_hold',
        ],
        'result_delivered' => [
            'visit_completed',
            'complaint_open',
        ],
        'visit_completed' => [
            'visit_closed',
            'complaint_open',
        ],
        'visit_closed' => [],
        'cancelled_by_hospital' => [
            'payment_refund_pending',
            'visit_closed',
        ],
        'cancelled_by_technician' => [
            'technician_reassignment_pending',
            'cancelled_by_hospital',
        ],
        'no_show_patient' => [],
        'no_show_technician' => [
            'reschedule_requested_by_patient',
            'arrival_breach',
            'technician_reassignment_pending',
            'cancelled_by_hospital',
        ],
        'payment_refund_pending' => [
            'payment_refunded',
            'escalation_open',
        ],
        'payment_refunded' => [],
        'complaint_open' => [
            'complaint_resolved',
            'escalation_open',
        ],
        'complaint_resolved' => [
            'visit_closed',
        ],
        'audit_hold' => [
            'visit_closed',
            'escalation_open',
            'escalation_unresolved',
        ],
        'escalation_open' => [
            'escalation_in_progress',
            'escalation_in_transfer',
            'escalation_resolved',
            'escalation_unresolved',
        ],
        'escalation_in_progress' => [
            'escalation_in_transfer',
            'escalation_resolved',
            'escalation_unresolved',
        ],
        'escalation_in_transfer' => [
            'escalation_resolved',
            'escalation_unresolved',
        ],
        'escalation_resolved' => [
            'visit_closed',
        ],
        'escalation_unresolved' => [],
    ],

    'allowed_actions_by_role' => [
        'awaiting_hospital_approval' => [
            'patient' => ['edit_request', 'cancel_request'],
            'hospital' => ['approve_request', 'request_changes', 'reject_request'],
        ],
        'hospital_changes_requested' => [
            'patient' => ['resubmit_request', 'cancel_request'],
            'hospital' => ['review_resubmission', 'reject_request'],
        ],
        'hospital_rejected' => [
            'patient' => ['rebook_test', 'contact_support'],
            'hospital' => ['view_audit'],
        ],
        'awaiting_technician_approval' => [
            'patient' => ['view_request', 'cancel_request'],
            'clinician' => ['accept_assignment', 'decline_assignment'],
            'hospital' => ['reassign_technician', 'cancel_request'],
        ],
        'technician_rejected' => [
            'patient' => ['wait_reassignment', 'cancel_request'],
            'hospital' => ['reassign_technician', 'reject_request'],
        ],
        'technician_reassignment_pending' => [
            'patient' => ['track_reassignment', 'cancel_request'],
            'clinician' => ['accept_assignment', 'decline_assignment'],
            'hospital' => ['assign_technician', 'escalate_ops', 'reject_request'],
        ],
        'awaiting_payment' => [
            'patient' => ['pay_now'],
            'hospital' => ['send_payment_reminder', 'cancel_request'],
        ],
        'payment_failed' => [
            'patient' => ['retry_payment', 'change_payment_method', 'cancel_request'],
            'hospital' => ['send_payment_link', 'cancel_request'],
        ],
        'payment_expired' => [
            'patient' => ['rebook_test', 'reopen_payment_session'],
            'hospital' => ['reopen_payment_session', 'close_request'],
        ],
        'scheduled' => [
            'patient' => ['track_visit', 'request_reschedule', 'cancel_request'],
            'clinician' => ['start_travel', 'view_visit_brief'],
            'hospital' => ['request_reschedule', 'reassign_technician', 'cancel_request'],
        ],
        'reschedule_requested_by_patient' => [
            'patient' => ['view_reschedule_request', 'cancel_reschedule'],
            'clinician' => ['accept_new_slot', 'decline_new_slot'],
            'hospital' => ['approve_reschedule', 'propose_alternative_slot', 'reject_reschedule'],
        ],
        'reschedule_requested_by_hospital' => [
            'patient' => ['accept_new_slot', 'request_another_slot', 'cancel_request'],
            'clinician' => ['confirm_availability', 'decline_new_slot'],
            'hospital' => ['finalize_new_slot', 'send_alternative_slot', 'revert_original_slot'],
        ],
        'reschedule_requested_by_technician' => [
            'patient' => ['accept_new_slot', 'request_another_slot', 'cancel_request'],
            'clinician' => ['view_reschedule_request'],
            'hospital' => ['approve_reschedule', 'reassign_technician', 'reject_reschedule'],
        ],
        'rescheduled_confirmed' => [
            'patient' => ['track_visit', 'view_updated_details'],
            'clinician' => ['start_travel', 'view_visit_brief'],
            'hospital' => ['monitor_eta', 'reassign_technician'],
        ],
        'en_route' => [
            'patient' => ['track_eta', 'contact_support'],
            'clinician' => ['mark_arrived', 'report_delay'],
            'hospital' => ['intervene_dispatch', 'reassign_technician'],
        ],
        'arrival_breach' => [
            'patient' => ['continue_waiting', 'request_reschedule', 'cancel_request'],
            'clinician' => ['update_eta'],
            'hospital' => ['reassign_technician', 'offer_reschedule', 'offer_compensation'],
        ],
        'arrived' => [
            'patient' => ['confirm_check_in'],
            'clinician' => ['start_visit'],
            'hospital' => ['monitor_check_in', 'intervene_check_in_delay'],
        ],
        'in_progress' => [
            'patient' => ['get_support'],
            'clinician' => ['complete_visit'],
            'hospital' => ['monitor_visit_sla'],
        ],
        'sample_collected' => [
            'patient' => ['track_result'],
            'clinician' => ['submit_handover'],
            'hospital' => ['monitor_lab_intake'],
        ],
        'sample_rejected' => [
            'patient' => ['view_rejection_reason', 'approve_recollection'],
            'clinician' => ['acknowledge_rejection'],
            'hospital' => ['initiate_recollection', 'escalate_quality_issue'],
        ],
        'recollection_required' => [
            'patient' => ['confirm_new_slot', 'contact_support'],
            'clinician' => ['accept_recollection'],
            'hospital' => ['schedule_recollection', 'reassign_technician'],
        ],
        'lab_processing' => [
            'patient' => ['track_result'],
            'clinician' => [],
            'hospital' => ['monitor_processing_sla', 'escalate_delay'],
        ],
        'result_ready' => [
            'patient' => ['view_result'],
            'clinician' => [],
            'hospital' => ['notify_patient'],
        ],
        'result_delivered' => [
            'patient' => ['view_result', 'open_record'],
            'clinician' => [],
            'hospital' => ['confirm_delivery_receipt'],
        ],
        'visit_completed' => [
            'patient' => ['review_technician', 'view_record'],
            'clinician' => [],
            'hospital' => ['view_audit'],
        ],
        'visit_closed' => [
            'patient' => ['view_history'],
            'clinician' => [],
            'hospital' => ['archive_case'],
        ],
        'cancelled_by_hospital' => [
            'patient' => ['rebook_test', 'contact_support'],
            'clinician' => [],
            'hospital' => ['record_cancellation_reason'],
        ],
        'cancelled_by_technician' => [
            'patient' => ['wait_reassignment', 'rebook_test'],
            'clinician' => ['submit_cancellation_reason'],
            'hospital' => ['reassign_technician', 'cancel_request'],
        ],
        'no_show_patient' => [
            'patient' => ['rebook_test', 'open_dispute'],
            'clinician' => ['mark_no_show'],
            'hospital' => ['review_no_show_evidence'],
        ],
        'no_show_technician' => [
            'patient' => ['request_reschedule', 'cancel_request', 'contact_support'],
            'clinician' => [],
            'hospital' => ['reassign_urgent', 'offer_compensation'],
        ],
        'payment_refund_pending' => [
            'patient' => ['track_refund'],
            'clinician' => [],
            'hospital' => ['process_refund'],
        ],
        'payment_refunded' => [
            'patient' => ['view_receipt', 'rebook_test'],
            'clinician' => [],
            'hospital' => ['view_ledger'],
        ],
        'complaint_open' => [
            'patient' => ['view_complaint'],
            'clinician' => ['submit_response'],
            'hospital' => ['investigate_complaint', 'resolve_complaint'],
        ],
        'complaint_resolved' => [
            'patient' => ['view_outcome'],
            'clinician' => [],
            'hospital' => ['archive_case'],
        ],
        'audit_hold' => [
            'patient' => ['view_status'],
            'clinician' => [],
            'hospital' => ['release_hold', 'escalate_compliance'],
        ],
        'escalation_open' => [
            'patient' => ['track_escalation', 'contact_support'],
            'clinician' => ['add_incident_note', 'request_transfer'],
            'hospital' => ['assign_escalation_lead', 'start_escalation_response'],
        ],
        'escalation_in_progress' => [
            'patient' => ['view_live_updates', 'contact_support'],
            'clinician' => ['update_incident', 'request_backup'],
            'hospital' => ['coordinate_response', 'escalate_transfer'],
        ],
        'escalation_in_transfer' => [
            'patient' => ['view_transfer_status'],
            'clinician' => ['confirm_handoff'],
            'hospital' => ['confirm_destination', 'close_transfer'],
        ],
        'escalation_resolved' => [
            'patient' => ['continue_care', 'view_summary'],
            'clinician' => ['acknowledge_closure'],
            'hospital' => ['close_incident', 'review_rca'],
        ],
        'escalation_unresolved' => [
            'patient' => ['view_outcome', 'contact_support'],
            'clinician' => ['submit_final_note'],
            'hospital' => ['escalate_compliance', 'terminate_case'],
        ],
    ],

    'action_targets' => [
        'edit_request' => '__stay',
        'cancel_request' => 'cancelled_by_hospital',
        'approve_request' => 'awaiting_technician_approval',
        'request_changes' => 'hospital_changes_requested',
        'reject_request' => 'hospital_rejected',
        'resubmit_request' => 'awaiting_hospital_approval',
        'review_resubmission' => '__stay',
        'view_audit' => '__stay',
        'view_request' => '__stay',
        'accept_assignment' => 'awaiting_payment',
        'decline_assignment' => 'technician_rejected',
        'reassign_technician' => 'technician_reassignment_pending',
        'wait_reassignment' => '__stay',
        'track_reassignment' => '__stay',
        'assign_technician' => 'awaiting_technician_approval',
        'escalate_ops' => 'escalation_open',
        'pay_now' => 'scheduled',
        'send_payment_reminder' => '__stay',
        'retry_payment' => 'awaiting_payment',
        'change_payment_method' => '__stay',
        'send_payment_link' => 'awaiting_payment',
        'rebook_test' => '__stay',
        'reopen_payment_session' => 'awaiting_payment',
        'close_request' => 'payment_expired',
        'track_visit' => '__stay',
        'view_updated_details' => '__stay',
        'request_reschedule' => '__dynamic_reschedule',
        'start_travel' => 'en_route',
        'view_visit_brief' => '__stay',
        'monitor_eta' => '__stay',
        'view_reschedule_request' => '__stay',
        'cancel_reschedule' => 'scheduled',
        'accept_new_slot' => 'rescheduled_confirmed',
        'decline_new_slot' => 'scheduled',
        'approve_reschedule' => 'rescheduled_confirmed',
        'propose_alternative_slot' => 'reschedule_requested_by_hospital',
        'reject_reschedule' => 'scheduled',
        'request_another_slot' => 'reschedule_requested_by_patient',
        'confirm_availability' => 'rescheduled_confirmed',
        'finalize_new_slot' => 'rescheduled_confirmed',
        'send_alternative_slot' => 'reschedule_requested_by_hospital',
        'revert_original_slot' => 'scheduled',
        'track_eta' => '__stay',
        'contact_support' => '__stay',
        'mark_arrived' => 'arrived',
        'report_delay' => 'arrival_breach',
        'intervene_dispatch' => '__stay',
        'continue_waiting' => 'en_route',
        'offer_reschedule' => 'rescheduled_confirmed',
        'offer_compensation' => '__stay',
        'update_eta' => 'en_route',
        'confirm_check_in' => 'in_progress',
        'start_visit' => 'in_progress',
        'monitor_check_in' => '__stay',
        'intervene_check_in_delay' => 'arrival_breach',
        'get_support' => '__stay',
        'complete_visit' => 'sample_collected',
        'monitor_visit_sla' => '__stay',
        'track_result' => '__stay',
        'submit_handover' => 'lab_processing',
        'monitor_lab_intake' => '__stay',
        'view_rejection_reason' => '__stay',
        'approve_recollection' => 'recollection_required',
        'acknowledge_rejection' => '__stay',
        'initiate_recollection' => 'recollection_required',
        'escalate_quality_issue' => 'escalation_open',
        'confirm_new_slot' => 'scheduled',
        'accept_recollection' => 'scheduled',
        'schedule_recollection' => 'scheduled',
        'monitor_processing_sla' => '__stay',
        'escalate_delay' => 'escalation_open',
        'view_result' => '__stay',
        'notify_patient' => 'result_delivered',
        'open_record' => 'visit_completed',
        'confirm_delivery_receipt' => 'visit_completed',
        'review_technician' => '__stay',
        'view_record' => '__stay',
        'view_history' => '__stay',
        'archive_case' => 'visit_closed',
        'record_cancellation_reason' => '__stay',
        'submit_cancellation_reason' => '__stay',
        'mark_no_show' => 'no_show_patient',
        'open_dispute' => '__stay',
        'review_no_show_evidence' => '__stay',
        'reassign_urgent' => 'technician_reassignment_pending',
        'track_refund' => '__stay',
        'process_refund' => 'payment_refunded',
        'view_receipt' => '__stay',
        'view_ledger' => '__stay',
        'view_complaint' => '__stay',
        'submit_response' => '__stay',
        'investigate_complaint' => '__stay',
        'resolve_complaint' => 'complaint_resolved',
        'view_outcome' => '__stay',
        'view_status' => '__stay',
        'release_hold' => 'visit_closed',
        'escalate_compliance' => 'escalation_unresolved',
        'track_escalation' => '__stay',
        'add_incident_note' => '__stay',
        'request_transfer' => 'escalation_in_transfer',
        'assign_escalation_lead' => 'escalation_in_progress',
        'start_escalation_response' => 'escalation_in_progress',
        'view_live_updates' => '__stay',
        'update_incident' => '__stay',
        'request_backup' => '__stay',
        'coordinate_response' => '__stay',
        'escalate_transfer' => 'escalation_in_transfer',
        'view_transfer_status' => '__stay',
        'confirm_handoff' => 'escalation_resolved',
        'confirm_destination' => '__stay',
        'close_transfer' => 'escalation_resolved',
        'continue_care' => 'visit_closed',
        'view_summary' => '__stay',
        'acknowledge_closure' => '__stay',
        'close_incident' => 'escalation_resolved',
        'review_rca' => '__stay',
        'submit_final_note' => 'escalation_unresolved',
        'terminate_case' => 'escalation_unresolved',
    ],

    'sla_windows' => [
        'awaiting_hospital_approval' => ['first_response_minutes' => 15, 'decision_minutes' => 120],
        'hospital_changes_requested' => ['patient_update_minutes' => 1440],
        'awaiting_technician_approval' => ['technician_response_minutes' => 15],
        'technician_reassignment_pending' => ['reassignment_minutes' => 30],
        'awaiting_payment' => ['payment_window_minutes' => 30],
        'payment_failed' => ['retry_within_window' => true],
        'scheduled' => ['travel_start_lead_minutes' => 15],
        'reschedule_requested_by_patient' => ['decision_minutes' => 30],
        'reschedule_requested_by_hospital' => ['decision_minutes' => 30],
        'reschedule_requested_by_technician' => ['hospital_response_minutes' => 15, 'resolution_minutes' => 30],
        'en_route' => ['eta_refresh_minutes' => 5, 'lateness_threshold_minutes' => 30],
        'arrival_breach' => ['ops_resolution_minutes' => 15],
        'arrived' => ['checkin_window_minutes' => 10],
        'sample_collected' => ['lab_intake_minutes' => 120],
        'sample_rejected' => ['recollection_initiation_minutes' => 240],
        'recollection_required' => ['slot_confirmation_minutes' => 360],
        'result_ready' => ['notify_immediately' => true],
        'visit_completed' => ['review_prompt_minutes' => 1440],
        'payment_refund_pending' => ['provider_settlement_days' => '3-10'],
        'complaint_open' => ['initial_triage_minutes' => 1440],
        'escalation_open' => ['initial_triage_minutes' => 5],
    ],

    'terminal_statuses' => [
        'hospital_rejected',
        'visit_closed',
        'no_show_patient',
        'payment_refunded',
        'escalation_unresolved',
    ],

    'status_aliases' => [
        'requested' => 'awaiting_hospital_approval',
        'pending' => 'awaiting_payment',
        'confirmed' => 'scheduled',
        'assigned' => 'awaiting_technician_approval',
        'result_uploaded' => 'result_ready',
        'validated' => 'result_delivered',
        'completed' => 'visit_completed',
        'cancelled' => 'cancelled_by_hospital',
        'no_show' => 'no_show_patient',
        'escalation in progress' => 'escalation_in_progress',
        'escalation in transfer' => 'escalation_in_transfer',
        'payment_refund_pending' => 'payment_refund_pending',
        'payment_refunded' => 'payment_refunded',
        'result delivered' => 'result_delivered',
        'result_delivered' => 'result_delivered',
    ],
];
