<?php

return [
    'enabled' => env('VIRTUAL_VISIT_WORKFLOW_V1', true),

    'workbook_path' => env('VIRTUAL_VISIT_WORKFLOW_WORKBOOK_PATH', '/Users/digitalfactory/Downloads/virtual visit workflow (1).xlsx'),
    'workbook_synced_at' => '2026-03-14',

    'statuses' => [
        'requested' => ['label' => 'Request Submitted'],
        'pending_review' => ['label' => 'Hospital Review'],
        'awaiting_clinician_approval' => ['label' => 'Awaiting Clinician Approval'],
        'reschedule_requested' => ['label' => 'Reschedule Requested'],
        'rescheduled_confirmed' => ['label' => 'Reschedule Confirmed'],
        'pending_payment' => ['label' => 'Payment Required'],
        'payment_failed' => ['label' => 'Payment Failed'],
        'payment_expired' => ['label' => 'Payment Expired'],
        'scheduled' => ['label' => 'Scheduled'],
        'waiting_room_open' => ['label' => 'Waiting Room Open'],
        'queued_for_clinician' => ['label' => 'Queued For Clinician'],
        'clinician_admitted_patient' => ['label' => 'Clinician Admitted Patient'],
        'consent_pending' => ['label' => 'Consent Pending'],
        'consent_granted' => ['label' => 'Consent Granted'],
        'session_link_sent' => ['label' => 'Session Link Sent'],
        'session_ready' => ['label' => 'Session Ready'],
        'clinician_joined' => ['label' => 'Clinician Joined'],
        'session_live' => ['label' => 'Session Live'],
        'in_progress' => ['label' => 'Consultation In Progress'],
        'session_interrupted' => ['label' => 'Session Interrupted'],
        'session_failed' => ['label' => 'Session Failed'],
        'clinical_closeout_pending' => ['label' => 'Clinical Closeout Pending'],
        'completed' => ['label' => 'Completed'],
        'session_ended' => ['label' => 'Session Ended'],
        'review_pending' => ['label' => 'Review Pending'],
        'record_released' => ['label' => 'Record Released'],
        'cancelled_by_patient' => ['label' => 'Cancelled by Patient'],
        'cancelled_by_clinician' => ['label' => 'Cancelled by Clinician'],
        'cancelled_by_hospital' => ['label' => 'Cancelled by Hospital'],
        'no_show_patient' => ['label' => 'No Show Patient'],
        'no_show_clinician' => ['label' => 'No Show Clinician'],
        'refund_pending' => ['label' => 'Refund Pending'],
        'refunded' => ['label' => 'Refunded'],
        'escalation_open' => ['label' => 'Escalation Open'],
        'escalation_in_progress' => ['label' => 'Escalation In Progress'],
        'escalation_resolved' => ['label' => 'Escalation Resolved'],
        'escalation_unresolved' => ['label' => 'Escalation Unresolved'],
        'dispute_open' => ['label' => 'Dispute Open'],
        'dispute_resolved' => ['label' => 'Dispute Resolved'],
        'failed' => ['label' => 'Failed'],
        'closed' => ['label' => 'Closed'],
    ],

    'allowed_transitions' => [
        'requested' => ['awaiting_clinician_approval', 'cancelled_by_patient', 'cancelled_by_hospital'],
        'pending_review' => ['awaiting_clinician_approval', 'cancelled_by_patient', 'cancelled_by_hospital'],
        'awaiting_clinician_approval' => ['pending_payment', 'scheduled', 'pending_review', 'cancelled_by_patient', 'cancelled_by_hospital'],
        'reschedule_requested' => ['rescheduled_confirmed', 'pending_review', 'scheduled', 'cancelled_by_hospital'],
        'rescheduled_confirmed' => ['pending_payment'],
        'pending_payment' => ['scheduled', 'payment_failed', 'payment_expired', 'cancelled_by_hospital'],
        'payment_failed' => ['pending_payment', 'payment_expired', 'cancelled_by_patient', 'cancelled_by_hospital'],
        'payment_expired' => ['pending_payment', 'closed'],
        'scheduled' => ['waiting_room_open'],
        'waiting_room_open' => ['queued_for_clinician'],
        'queued_for_clinician' => ['clinician_admitted_patient'],
        'clinician_admitted_patient' => ['consent_pending'],
        'consent_pending' => ['consent_granted'],
        'consent_granted' => ['session_link_sent'],
        'session_link_sent' => ['session_ready'],
        'session_ready' => ['clinician_joined'],
        'clinician_joined' => ['session_live'],
        'session_live' => ['in_progress'],
        'in_progress' => ['clinical_closeout_pending'],
        'session_interrupted' => ['in_progress'],
        'session_failed' => ['failed', 'escalation_open'],
        'clinical_closeout_pending' => ['completed'],
        'completed' => ['review_pending'],
        'session_ended' => ['clinical_closeout_pending'],
        'review_pending' => ['record_released'],
        'record_released' => ['closed'],
        'cancelled_by_patient' => ['refund_pending'],
        'cancelled_by_clinician' => ['refund_pending'],
        'cancelled_by_hospital' => ['refund_pending'],
        'no_show_patient' => ['closed', 'dispute_open'],
        'no_show_clinician' => ['refund_pending'],
        'refund_pending' => ['refunded'],
        'refunded' => ['closed'],
        'escalation_open' => ['escalation_in_progress'],
        'escalation_in_progress' => ['escalation_resolved'],
        'escalation_resolved' => ['closed'],
        'escalation_unresolved' => ['failed'],
        'dispute_open' => ['dispute_resolved'],
        'dispute_resolved' => ['closed'],
        'failed' => ['closed'],
        'closed' => [],
    ],

    'allowed_actions_by_role' => [
        'requested' => [
            'patient' => ['edit_request', 'cancel_request'],
            'hospital' => ['approve', 'request_changes', 'reject'],
        ],
        'pending_review' => [
            'patient' => ['wait', 'cancel_request'],
            'hospital' => ['approve', 'request_changes', 'reject'],
        ],
        'awaiting_clinician_approval' => [
            'patient' => ['wait', 'cancel_request'],
            'clinician' => ['accept', 'decline'],
            'hospital' => ['reassign', 'cancel_request'],
        ],
        'reschedule_requested' => [
            'patient' => ['view_request', 'cancel_reschedule'],
            'clinician' => ['accept_new_slot', 'decline'],
            'hospital' => ['approve_slot', 'propose_alternative', 'reject'],
        ],
        'rescheduled_confirmed' => [
            'patient' => ['view_updated_schedule'],
            'clinician' => ['view_updated_slot'],
            'hospital' => ['monitor_schedule'],
        ],
        'pending_payment' => [
            'patient' => ['pay_now'],
            'hospital' => ['send_reminder', 'cancel_request'],
        ],
        'payment_failed' => [
            'patient' => ['retry_payment', 'change_method', 'cancel_request'],
            'hospital' => ['send_payment_link', 'cancel_request'],
        ],
        'payment_expired' => [
            'patient' => ['rebook', 'retry_payment'],
            'hospital' => ['reopen_payment', 'close_request'],
        ],
        'scheduled' => [
            'patient' => ['prepare', 'track_session'],
            'clinician' => ['view_schedule'],
            'hospital' => ['monitor_queue'],
        ],
        'waiting_room_open' => [
            'patient' => ['join_waiting_room'],
            'clinician' => ['open_queue'],
            'hospital' => ['monitor_queue'],
        ],
        'queued_for_clinician' => [
            'patient' => ['wait'],
            'clinician' => ['admit_patient'],
            'hospital' => ['monitor_queue'],
        ],
        'clinician_admitted_patient' => [
            'patient' => ['continue'],
            'clinician' => ['start_session_setup'],
            'hospital' => ['observe_session_start'],
        ],
        'consent_pending' => [
            'patient' => ['provide_consent'],
            'clinician' => ['wait_for_consent'],
            'hospital' => ['monitor_compliance'],
        ],
        'consent_granted' => [
            'patient' => ['continue'],
            'clinician' => ['send_session_link'],
            'hospital' => ['audit_consent'],
        ],
        'session_link_sent' => [
            'patient' => ['open_session'],
            'clinician' => ['open_session_console'],
            'hospital' => ['verify_delivery'],
        ],
        'session_ready' => [
            'patient' => ['join_session'],
            'clinician' => ['join_session'],
            'hospital' => ['watch_join_sla'],
        ],
        'clinician_joined' => [
            'patient' => ['join_now'],
            'clinician' => ['start_consultation'],
            'hospital' => ['monitor_session'],
        ],
        'session_live' => [
            'patient' => ['continue_session'],
            'clinician' => ['document_notes'],
            'hospital' => ['monitor_quality'],
        ],
        'in_progress' => [
            'patient' => ['get_support'],
            'clinician' => ['complete_consultation'],
            'hospital' => ['monitor_consult'],
        ],
        'session_interrupted' => [
            'patient' => ['reconnect'],
            'clinician' => ['reconnect_session'],
            'hospital' => ['observe_recovery'],
        ],
        'session_failed' => [
            'patient' => ['reschedule', 'contact_support'],
            'clinician' => ['file_failure_report'],
            'hospital' => ['recover_flow', 'escalate'],
        ],
        'clinical_closeout_pending' => [
            'patient' => ['wait'],
            'clinician' => ['submit_report'],
            'hospital' => ['validate_closeout'],
        ],
        'completed' => [
            'patient' => ['review_carer'],
            'hospital' => ['audit_completion'],
        ],
        'session_ended' => [
            'patient' => ['view_summary'],
            'hospital' => ['archive_session_log'],
        ],
        'review_pending' => [
            'patient' => ['review_carer'],
            'hospital' => ['monitor_reviews'],
        ],
        'record_released' => [
            'patient' => ['view_record'],
            'hospital' => ['track_access'],
        ],
        'cancelled_by_patient' => [
            'patient' => ['rebook'],
            'hospital' => ['review_cancellation'],
        ],
        'cancelled_by_clinician' => [
            'patient' => ['rebook', 'contact_support'],
            'clinician' => ['submit_reason'],
            'hospital' => ['reassign', 'approve_refund'],
        ],
        'cancelled_by_hospital' => [
            'patient' => ['rebook', 'contact_support'],
            'hospital' => ['record_reason', 'approve_refund'],
        ],
        'no_show_patient' => [
            'patient' => ['rebook', 'dispute'],
            'clinician' => ['mark_no_show'],
            'hospital' => ['validate_no_show'],
        ],
        'no_show_clinician' => [
            'patient' => ['reschedule', 'cancel', 'contact_support'],
            'hospital' => ['reassign', 'compensate'],
        ],
        'refund_pending' => [
            'patient' => ['track_refund'],
            'hospital' => ['process_refund'],
        ],
        'refunded' => [
            'patient' => ['view_receipt', 'rebook'],
            'hospital' => ['close_finance_case'],
        ],
        'escalation_open' => [
            'patient' => ['track_escalation', 'contact_support'],
            'clinician' => ['add_incident_note', 'request_senior_support'],
            'hospital' => ['assign_lead', 'start_response'],
        ],
        'escalation_in_progress' => [
            'patient' => ['view_updates', 'contact_support'],
            'clinician' => ['update_incident', 'request_backup'],
            'hospital' => ['coordinate_response', 'decide_outcome'],
        ],
        'escalation_resolved' => [
            'patient' => ['continue', 'view_incident_summary'],
            'clinician' => ['acknowledge_closure'],
            'hospital' => ['close_incident'],
        ],
        'escalation_unresolved' => [
            'patient' => ['view_outcome', 'contact_support'],
            'clinician' => ['submit_final_note'],
            'hospital' => ['escalate_compliance', 'terminate_case'],
        ],
        'dispute_open' => [
            'patient' => ['view_dispute'],
            'clinician' => ['submit_response'],
            'hospital' => ['investigate', 'resolve'],
        ],
        'dispute_resolved' => [
            'patient' => ['view_outcome'],
            'hospital' => ['archive_case'],
        ],
        'failed' => [
            'patient' => ['rebook', 'contact_support'],
            'clinician' => ['submit_failure_summary'],
            'hospital' => ['classify_failure', 'recover'],
        ],
        'closed' => [
            'patient' => ['view_history'],
            'hospital' => ['archive'],
        ],
    ],

    'action_targets' => [
        'accept' => 'pending_payment',
        'accept_new_slot' => '__stay',
        'acknowledge_closure' => 'escalation_resolved',
        'add_incident_note' => '__stay',
        'admit_patient' => 'clinician_admitted_patient',
        'approve' => 'awaiting_clinician_approval',
        'approve_refund' => 'refund_pending',
        'approve_slot' => 'rescheduled_confirmed',
        'archive' => 'closed',
        'archive_case' => 'closed',
        'archive_session_log' => 'clinical_closeout_pending',
        'assign_lead' => 'escalation_in_progress',
        'audit_completion' => '__stay',
        'audit_consent' => '__stay',
        'cancel' => 'refund_pending',
        'cancel_request' => '__dynamic_cancel_request',
        'cancel_reschedule' => 'scheduled',
        'change_method' => 'pending_payment',
        'classify_failure' => 'failed',
        'close_finance_case' => 'closed',
        'close_incident' => 'escalation_resolved',
        'close_request' => 'closed',
        'compensate' => '__stay',
        'complete_consultation' => 'clinical_closeout_pending',
        'contact_support' => '__stay',
        'continue' => '__stay',
        'continue_session' => '__stay',
        'coordinate_response' => '__stay',
        'decide_outcome' => 'escalation_resolved',
        'decline' => 'pending_review',
        'dispute' => 'dispute_open',
        'document_notes' => '__stay',
        'edit_request' => '__stay',
        'escalate' => 'escalation_open',
        'escalate_compliance' => 'escalation_unresolved',
        'file_failure_report' => '__stay',
        'get_support' => '__stay',
        'investigate' => '__stay',
        'join_now' => '__stay',
        'join_session' => '__stay',
        'join_waiting_room' => 'queued_for_clinician',
        'mark_no_show' => 'no_show_patient',
        'monitor_compliance' => '__stay',
        'monitor_consult' => '__stay',
        'monitor_quality' => '__stay',
        'monitor_queue' => '__stay',
        'monitor_reviews' => '__stay',
        'monitor_schedule' => '__stay',
        'monitor_session' => '__stay',
        'observe_recovery' => '__stay',
        'observe_session_start' => '__stay',
        'open_queue' => '__stay',
        'open_session' => '__stay',
        'open_session_console' => '__stay',
        'pay_now' => 'scheduled',
        'prepare' => '__stay',
        'process_refund' => 'refunded',
        'propose_alternative' => 'reschedule_requested',
        'provide_consent' => 'consent_granted',
        'reassign' => '__dynamic_reassign',
        'rebook' => '__stay',
        'reconnect' => 'in_progress',
        'reconnect_session' => 'in_progress',
        'record_reason' => '__stay',
        'recover' => 'closed',
        'recover_flow' => 'failed',
        'reject' => 'cancelled_by_hospital',
        'reopen_payment' => 'pending_payment',
        'request_backup' => '__stay',
        'request_changes' => 'pending_review',
        'request_senior_support' => 'escalation_in_progress',
        'reschedule' => '__stay',
        'resolve' => 'dispute_resolved',
        'retry_payment' => 'pending_payment',
        'review_cancellation' => '__stay',
        'review_carer' => 'review_pending',
        'send_payment_link' => 'pending_payment',
        'send_reminder' => 'pending_payment',
        'send_session_link' => 'session_link_sent',
        'start_consultation' => 'session_live',
        'start_response' => 'escalation_in_progress',
        'start_session_setup' => 'consent_pending',
        'submit_failure_summary' => '__stay',
        'submit_final_note' => '__stay',
        'submit_reason' => '__stay',
        'submit_report' => 'completed',
        'submit_response' => '__stay',
        'terminate_case' => 'escalation_unresolved',
        'track_access' => '__stay',
        'track_escalation' => '__stay',
        'track_refund' => '__stay',
        'track_session' => '__stay',
        'update_incident' => '__stay',
        'validate_closeout' => '__stay',
        'validate_no_show' => '__stay',
        'verify_delivery' => '__stay',
        'view_dispute' => '__stay',
        'view_history' => '__stay',
        'view_incident_summary' => '__stay',
        'view_outcome' => '__stay',
        'view_receipt' => '__stay',
        'view_record' => '__stay',
        'view_request' => '__stay',
        'view_schedule' => '__stay',
        'view_summary' => '__stay',
        'view_updated_schedule' => '__stay',
        'view_updated_slot' => '__stay',
        'view_updates' => '__stay',
        'wait' => '__stay',
        'wait_for_consent' => '__stay',
        'watch_join_sla' => '__stay',
    ],

    'sla_windows' => [
        'requested' => ['target' => 'Auto-triage start immediately; triage decision target <=2 hours.'],
        'pending_review' => ['target' => 'Review completion target <=2 hours.'],
        'awaiting_clinician_approval' => ['target' => 'Clinician response SLA <=15 minutes.'],
        'reschedule_requested' => ['target' => 'Reschedule resolution target <=30 minutes.'],
        'rescheduled_confirmed' => ['target' => 'Update notifications should be sent immediately.'],
        'pending_payment' => [
            'target' => 'Payment window e.g. 15-30 minutes.',
            'payment_window_minutes' => (int) env('VIRTUAL_VISIT_PAYMENT_WINDOW_MINUTES', 30),
        ],
        'payment_failed' => ['target' => 'Retry window remains within payment expiry SLA.'],
        'payment_expired' => ['target' => 'Auto-expire at configured timeout.'],
        'scheduled' => ['target' => 'Session setup should begin before join window opens.'],
        'waiting_room_open' => [
            'target' => 'Waiting room should open at configured lead time (e.g., 15 minutes before session).',
            'open_lead_minutes' => (int) env('VIRTUAL_VISIT_WAITING_ROOM_OPEN_LEAD_MINUTES', 15),
            'timezone' => env('VIRTUAL_VISIT_WAITING_ROOM_TIMEZONE', 'Africa/Lagos'),
        ],
        'queued_for_clinician' => [
            'target' => 'Queue wait SLA e.g. <=10 minutes.',
            'queue_wait_minutes' => (int) env('VIRTUAL_VISIT_QUEUE_WAIT_MINUTES', 10),
        ],
        'clinician_admitted_patient' => ['target' => 'Session setup should begin immediately after admission.'],
        'consent_pending' => ['target' => 'Consent should be completed quickly before session start.'],
        'consent_granted' => ['target' => 'Session link dispatch should be immediate.'],
        'session_link_sent' => ['target' => 'Delivery confirmation target <=1 minute.'],
        'session_ready' => ['target' => 'Participant join SLA should be enforced.'],
        'clinician_joined' => ['target' => 'Patient should join within configured grace window.'],
        'session_live' => ['target' => 'Session heartbeat should remain active during consult.'],
        'in_progress' => ['target' => 'Consult should complete within planned duration or capture overrun reason.'],
        'session_interrupted' => [
            'target' => 'Reconnection should occur within short SLA (e.g., <=2 minutes).',
            'reconnect_minutes' => (int) env('VIRTUAL_VISIT_RECONNECT_MINUTES', 2),
        ],
        'session_failed' => ['target' => 'Failure handling should begin immediately.'],
        'clinical_closeout_pending' => [
            'target' => 'Closeout should be submitted promptly (e.g., <=15 minutes).',
            'closeout_minutes' => (int) env('VIRTUAL_VISIT_CLOSEOUT_MINUTES', 15),
        ],
        'completed' => ['target' => 'Completion notification should be immediate.'],
        'session_ended' => ['target' => 'Session end event should be written immediately.'],
        'review_pending' => [
            'target' => 'First reminder within 1 hour; follow-up at 24 hours.',
            'first_reminder_minutes' => (int) env('VIRTUAL_VISIT_REVIEW_FIRST_REMINDER_MINUTES', 60),
        ],
        'record_released' => ['target' => 'Record should be released immediately after gate conditions are met.'],
        'cancelled_by_patient' => ['target' => 'Cancellation acknowledgement should be immediate.'],
        'cancelled_by_clinician' => ['target' => 'Patient should be notified immediately.'],
        'cancelled_by_hospital' => ['target' => 'Patient notification should be immediate.'],
        'no_show_patient' => ['target' => 'No-show decision should be finalized quickly.'],
        'no_show_clinician' => ['target' => 'Recovery should begin immediately.'],
        'refund_pending' => ['target' => 'Provider settlement SLA typically 3-10 business days.'],
        'refunded' => ['target' => 'Patient should be notified immediately after confirmation.'],
        'escalation_open' => ['target' => 'Initial response should begin immediately (e.g., <=5 minutes for high severity).'],
        'escalation_in_progress' => ['target' => 'High-severity cases require continuous update cadence.'],
        'escalation_resolved' => ['target' => 'Resolution notice should be immediate.'],
        'escalation_unresolved' => ['target' => 'Unresolved closure requires authorized approval.'],
        'dispute_open' => ['target' => 'Initial triage should begin within support SLA (e.g., <=24 hours).'],
        'dispute_resolved' => ['target' => 'Resolution notice should be sent immediately.'],
        'failed' => ['target' => 'Failure handling should start immediately.'],
        'closed' => ['target' => 'Closure should occur immediately after terminal condition is met.'],
    ],

    'terminal_statuses' => [
        'closed',
    ],

    'status_aliases' => [
        'pending' => 'pending_review',
        'confirmed' => 'scheduled',
        'cancelled' => 'cancelled_by_hospital',
        'no_show' => 'no_show_patient',
        'reviewed' => 'record_released',
    ],

    'workbook_statuses' => [
        'requested',
        'pending_review',
        'awaiting_clinician_approval',
        'reschedule_requested',
        'rescheduled_confirmed',
        'pending_payment',
        'payment_failed',
        'payment_expired',
        'scheduled',
        'waiting_room_open',
        'queued_for_clinician',
        'clinician_admitted_patient',
        'consent_pending',
        'consent_granted',
        'session_link_sent',
        'session_ready',
        'clinician_joined',
        'session_live',
        'in_progress',
        'session_interrupted',
        'session_failed',
        'clinical_closeout_pending',
        'completed',
        'session_ended',
        'review_pending',
        'record_released',
        'cancelled_by_patient',
        'cancelled_by_clinician',
        'cancelled_by_hospital',
        'no_show_patient',
        'no_show_clinician',
        'refund_pending',
        'refunded',
        'escalation_open',
        'escalation_in_progress',
        'escalation_resolved',
        'escalation_unresolved',
        'dispute_open',
        'dispute_resolved',
        'failed',
        'closed',
    ],
];
